from abc import ABC, abstractmethod
from typing import Iterable, Optional
from .entities import Product, Recipe, ShoppingList, RecipeItem

class ProductRepository(ABC):
    @abstractmethod
    def add(self, p: Product) -> Product: ...
    @abstractmethod
    def get(self, pid: int) -> Optional[Product]: ...
    @abstractmethod
    def list(self) -> Iterable[Product]: ...
    @abstractmethod
    def update(self, pid: int, p: Product) -> Product: ...
    @abstractmethod
    def delete(self, pid: int) -> None: ...
    @abstractmethod
    def exists_by_name(self, name: str) -> bool: ...

class RecipeRepository(ABC):
    @abstractmethod
    def add(self, r: Recipe) -> Recipe: ...
    @abstractmethod
    def get(self, rid: int) -> Optional[Recipe]: ...
    @abstractmethod
    def list(self) -> Iterable[Recipe]: ...

class ShoppingListRepository(ABC):
    @abstractmethod
    def add(self, s: ShoppingList) -> ShoppingList: ...
    @abstractmethod
    def get(self, lid: int) -> Optional[ShoppingList]: ...
    @abstractmethod
    def list(self) -> Iterable[ShoppingList]: ...
    @abstractmethod
    def add_item(self, lid: int, product_id: int, quantity: float) -> None: ...
